version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: Ticket-sales-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Ticket-sales-service
    ports:
      - "5432:5432"
    volumes:
      - ./common/src/main/java/ru/demanin/migration/create-table.sql:/docker-entrypoint-initdb.d/creating-table.sql